name: darak_project
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  get: ^4.6.5

  flutter_facebook_auth: ^3.5.0
  google_sign_in: ^6.1.0

  flutter_screenutil: ^5.6.1

  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  cloud_firestore: ^4.5.1
  firebase_storage: ^11.1.1
  firebase_messaging: ^14.4.1
  
  shared_preferences: ^2.1.0
  sqflite: ^2.2.6

  hexcolor: ^3.0.1

  flutter_otp_text_field: ^1.1.1

  pull_to_refresh: ^2.0.0

  intl: ^0.17.0

  permission_handler: ^10.2.0

  # Images
  cached_network_image: ^3.2.0
  image_picker: ^0.7.2+1
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.0.0+2
  flutter_svg: ^2.0.5
  path: ^1.8.1
  random_string: ^2.3.1
  photo_view: ^0.14.0

  chat_bubbles: ^1.4.0

  package_info_plus: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.jpg"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/
    - assets/icon/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Satoshi-Regular
      fonts:
        - asset: assets/font/Satoshi-Regular.otf

    - family: Satoshi-Medium
      fonts:
        - asset: assets/font/Satoshi-Medium.otf

    - family: Satoshi-Bold
      fonts:
        - asset: assets/font/Satoshi-Bold.otf


