// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiGn3-_CiET-e3hkgcnza-JAJyaOnMvMQ',
    appId: '1:970638981919:web:aba385cfe40368ea928e2a',
    messagingSenderId: '970638981919',
    projectId: 'cool-automata-380420',
    authDomain: 'cool-automata-380420.firebaseapp.com',
    storageBucket: 'cool-automata-380420.appspot.com',
    measurementId: 'G-07TTYX796Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz1FYuBFu4rLskQvGUr-t2nco0NI4_z1U',
    appId: '1:970638981919:android:55d0de3d62fda7f0928e2a',
    messagingSenderId: '970638981919',
    projectId: 'cool-automata-380420',
    storageBucket: 'cool-automata-380420.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtnwmkv9VudoqlXoevgJFvWyBxOH_XPio',
    appId: '1:970638981919:ios:35b52e84078c0871928e2a',
    messagingSenderId: '970638981919',
    projectId: 'cool-automata-380420',
    storageBucket: 'cool-automata-380420.appspot.com',
    iosClientId: '970638981919-q476vcj80s4glbihelm61eqsbvn2i942.apps.googleusercontent.com',
    iosBundleId: 'com.darakproject.darakProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtnwmkv9VudoqlXoevgJFvWyBxOH_XPio',
    appId: '1:970638981919:ios:35b52e84078c0871928e2a',
    messagingSenderId: '970638981919',
    projectId: 'cool-automata-380420',
    storageBucket: 'cool-automata-380420.appspot.com',
    iosClientId: '970638981919-q476vcj80s4glbihelm61eqsbvn2i942.apps.googleusercontent.com',
    iosBundleId: 'com.darakproject.darakProject',
  );
}
